dist: trusty
sudo: required
language: node_js
addons:
  chrome: stable
before_script:
  - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &

script:
  - yarn test
  - yarn lint
before_deploy: "./compile-build.sh release.tar.gz dist staging"
deploy:
  provider: releases
  api_key:
    secure: jbeqmYk6AVhZuJxNsIZ2nt5GiCuS8ap9ojRuV0T2pgSx+Z9D9Yve0O/iTPE2u5bsNMkDrvJFodndB1/T9Ya4Q34Zw6eVZ4kwTDiU+QdYd21lz80/bMHV18sVFpEBJa4QbEyyBo2pemCwDyupODRJIzrpC//GunyCyfD9X+ODisr7vdG6apOLvYYDpCzUGOReErRGQ4eapn1LdMgNzNySlN8lqbxvq2TFWR5Fa7yxJO/i91g2yvcDDmR4C4Ba7Wl4E/hdRemA+iv2K23L85pFTaoEqqZYusm3Z59Trt+pZczqCTe0r3SKpRZ0LsJ2N21oIKOy9Jopr+Mv8OfB3FDPlXzPgTw7Gl7hxD9OX/hKgAI6Ir8srRbN6UO8zDG/9UFrWSZiiAdT/mGFB96qd9VagJwG09+fQbcm0s5GBOG/fC9YC66VjaRRhtIrNnmN0xnNe38iQGMkX/aAfFaZf0ndDpIp/fWXdUJk4hzZRzOKwpXXVQyCQk8bRBbzhh9Nidb/L4mezkU5eAgvru+dZPmBrZsQAMXKUZb7kka7dJ/QFG/P4NTsAFtJ8xAMt6LlIR5E4FJ1w+yba+CYp42YeDC01vsjUXFsRHRduN9UtzE7kAxAN+iwsoCeX9Z/5STNllzqLCxyy4catL7YT2p75MT3RjI2H1IT3/WxH7iPGsXRTDw=
  file: release.tar.gz
  on:
    repo: sanger/traction-ui
    branch: devel
notifications:
  slack:
    secure: WZbwTFZ1hsylP7UTOXRPZOoUWw+X6GriinzmFTxRQGube2x3r2yJyrWM90txBsJVUR/s4rEaipl6vD+/UCVzkEbIaD3O66tcox4w+rqjpyet8qLBgV+y0f03NYvQ8sHckA6tOZWDaXxMSVAcP35i8VpvyHSeSoTqyM5LYuWaGpiWs/DSMdRmr3eCR4jFJfk7xDJMG6WgkCir+st9HyZuIJlDpQOfKMtPuziOQ5QxGM3dytJMUdspGDYKw4ZzfdY1fbVoMLCsw8kxJcdszylGYIPjpcxKYqVojA7K/mEjRaJNukZuYwu61rfLMWNqzxkydK+9R3N1QPwLIB/1rHZOde4PMUVjLSB09BiKWagzvrtpfzB5UdV81cJfo+GXch0XB7SWNeBJK79S43SgD5tYKNrs8s6hQj6xg8+3cnUM7Qa3yHP6XDGz5uyAreTj9SmLIXyFYMBWVkjj/j0kx9j6CZBs6BZkyfA/MuWnrgMbz52kWOte2/bJW4XcYF3Euq9XGX1dWN2MVEe+D+VeS/g9NuyHw7A956L0//ItXCZBNzzWfRQFXBJZexpTltvyFf4qQmkSWeDZ212yZgNN6MCumJbE0UaS4OBImmWkKYv05+Ztflr4WWpLwlzZ6fIRAG3LHNPlVoRb/pcT6BnBWZr/UwmczqOKXQpCFHIBc5doJIE=
